options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: echo-hello
    entrypoint: bash
    args:
      - -c
      - |
        echo "Hello from Cloud Build"
        echo "PROJECT_ID is: $PROJECT_ID"
        echo "REPO_NAME is: $REPO_NAME"
        echo "SHORT_SHA is: $SHORT_SHA"
