[build]
  base = "frontend_app"
  command = "npm install && npm run build"
  publish = "dist"

[[redirects]]
  from = "/finishSignIn"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/post"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/saved"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/my"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
