options:
  logging: "CLOUD_LOGGING_ONLY"

steps:
  # Step 1: Build the Docker image for the Concierge service
  - name: "gcr.io/cloud-builders/docker"
    id: "build-concierge"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/github.com/goflypost/v4/concierge:$SHORT_SHA"
      - "-f"
      - "widget/Dockerfile"
      - "widget"
    dir: "v4/concierge"

  # Step 2: Push the Docker image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    id: "push-concierge"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/github.com/goflypost/v4/concierge:$SHORT_SHA"

  # Step 3: Deploy the Concierge service to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy-concierge"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "flypost-concierge"
      - "--image"
      - "gcr.io/$PROJECT_ID/github.com/goflypost/v4/concierge:$SHORT_SHA"
      - "--region"
      - "us-west1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

images:
  - "gcr.io/$PROJECT_ID/github.com/goflypost/v4/concierge:$SHORT_SHA"
