steps:
  # Step 1: Build the Docker image for the concierge service
  - name: 'gcr.io/cloud-builders/docker'
    id: build-concierge
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/github.com/goflypost/v4/concierge:$SHORT_SHA", # Tag the image with the commit SHA
        "-f",
        "widget/Dockerfile", # Dockerfile location relative to the 'concierge' folder
        "widget",            # Build context
      ]
    dir: 'v4/concierge' # Start from this directory (path to widget)

  # Step 2: Push the Docker image to Google Container Registry or Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: push-concierge
    args:
      [
        "push",
        "gcr.io/$PROJECT_ID/github.com/goflypost/v4/concierge:$SHORT_SHA",
      ]

  # Step 3: Deploy the Concierge service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: deploy-concierge
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "flypost-concierge", # Deploy to the 'flypost-concierge' service
        "--image", "gcr.io/$PROJECT_ID/github.com/goflypost/v4/concierge:$SHORT_SHA", # Latest pushed image
        "--region", "us-west1", # Deployment region
        "--platform", "managed",
        "--allow-unauthenticated", # Allow public access to the Concierge service
      ]

# Outputs the final pushed Docker image
images:
  - "gcr.io/$PROJECT_ID/github.com/goflypost/v4/concierge:$SHORT_SHA"
