apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/build-enable-automatic-updates: 'false'
    run.googleapis.com/build-id: f4429b9a-2d79-4fd1-8d7d-d7d7bdf6c8c9
    run.googleapis.com/build-image-uri: us-west1-docker.pkg.dev/goflypost/cloud-run-source-deploy/proxyv4
    run.googleapis.com/build-name: projects/498798854474/locations/us-west1/builds/f4429b9a-2d79-4fd1-8d7d-d7d7bdf6c8c9
    run.googleapis.com/build-source-location: gs://run-sources-goflypost-us-west1/services/proxyv4/1783547790.773601-d616b680131f443f88443d6953d0c1e4.zip#1783547794856838
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/invoker-iam-disabled: 'true'
    run.googleapis.com/maxScale: '20'
    run.googleapis.com/urls: '["https://proxyv4-498798854474.us-west1.run.app","https://proxyv4-a7jlfl42zq-uw.a.run.app"]'
  labels:
    cloud.googleapis.com/location: us-west1
    commit-sha: 6590bd49adb12ecb15ac718614dfffdb0805022b
    gcb-build-id: 2bd32e22-2f54-4b96-9eff-3effa2996686
    gcb-trigger-id: ebbc10ba-4b01-4b34-916d-b108c485a0b1
    gcb-trigger-region: global
    managed-by: gcp-cloud-build-deploy-cloud-run
  name: proxyv4
  namespace: '498798854474'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '3'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 525.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: ardppgubwt
        commit-sha: 6590bd49adb12ecb15ac718614dfffdb0805022b
        gcb-build-id: 2bd32e22-2f54-4b96-9eff-3effa2996686
        gcb-trigger-id: ebbc10ba-4b01-4b34-916d-b108c485a0b1
        gcb-trigger-region: global
        managed-by: gcp-cloud-build-deploy-cloud-run
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: BACKEND_URL
          value: https://flypostv4-a7jlfl42zq-uw.a.run.app
        - name: FRONTEND_ORIGIN
          value: https://flypost.netlify.app,https://app.goflypost.com
        - name: PROXY_USE_ID_TOKEN
          value: 'true'
        - name: FIREBASE_PROJECT_ID
          value: goflypost
        image: us-west1-docker.pkg.dev/goflypost/cloud-run-source-deploy/proxyv4@sha256:2eb298d722483fdf0b140a2006a960b77b41dd961600059421acfafdfc6c4af8
        name: placeholder-1
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: flypost-proxy-service-account@goflypost.iam.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
